// <auto-generated />
namespace Bike2Go.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ExperienceTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExperienceTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711200927371_ExperienceTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
